version: "3.8"
services:
  nginx:
    image: nginx:1.17-alpine
    ports:
      - "80:80"
    volumes:
      - ./etc/infrastructure/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/app/public:ro
    depends_on:
      - php
  php:
    build:
      dockerfile: etc/artifacts/Dockerfile
      context: .
      target: dev
    environment:
      - XDEBUG_CLIENT_HOST=host.docker.internal
    volumes:
      - ./:/app:rw,delegated
