name: PHP CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.16'
          coverage: xdebug # or pcov for coverage

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v3
        with:
          file: coverage.xml
          flags: unittests
